### ISSUE TITLE
Unable to set up component :(

### ISSUE THREAD

**Issue by GeraldG007** [neilzilla/hass-renpho#12]
Hi,

not able to use it as currently i get these 3 errors:

1)

Unable to prepare setup for platform renpho.sensor: Unable to set up component.
21:53:50 – (FEHLER) setup.py

 Logger: homeassistant.setup
Source: setup.py:366
First occurred: 21:53:50 (1 occurrences)
Last logged: 21:53:50
Unable to prepare setup for platform renpho.sensor: Unable to set up component.

2)

Error during setup of component renpho
21:53:50 – (FEHLER) renpho (benutzerdefinierte Integration)
Logger: homeassistant.setup
Source: custom_components/renpho/api_renpho.py:173
Integration: renpho ([documentation](https://github.com/antoinebou12/hass_renpho), [issues](https://github.com/antoinebou12/hass_renpho/issues))
First occurred: 21:53:50 (1 occurrences)
Last logged: 21:53:50
Error during setup of component renpho

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 256, in _async_setup_component
    result = await task
  File "/config/custom_components/renpho/__init__.py", line 27, in async_setup
    await setup_renpho(hass, conf)
  File "/config/custom_components/renpho/__init__.py", line 61, in setup_renpho
    await renpho.get_info()
  File "/config/custom_components/renpho/api_renpho.py", line 331, in get_info
    await self.auth()
  File "/config/custom_components/renpho/api_renpho.py", line 173, in auth
    raise AuthenticationError("'terminal_user_session_key' missing.")
custom_components.renpho.api_renpho.AuthenticationError: 'terminal_user_session_key' missing

3)

'terminal_user_session_key' not found in parsed object.
21:53:50 – (FEHLER) renpho (benutzerdefinierte Integration)

Logger: custom_components.renpho.api_renpho
Source: custom_components/renpho/api_renpho.py:331
Integration: renpho ([documentation](https://github.com/antoinebou12/hass_renpho), [issues](https://github.com/antoinebou12/hass_renpho/issues))
First occurred: 21:53:50 (1 occurrences)
Last logged: 21:53:50
'terminal_user_session_key' not found in parsed object.

Any suggestions?

best thanks

best regards
Gerald

**Comment by scottsperry** [comment]
[https://github.com/antoinebou12/hass_renpho/issues/7](https://github.com/antoinebou12/hass_renpho/issues/7) has a better discussion of the issue


I get the same error.

The problem for me is:
{"status_code": "50000", "status_message": "Account does not exist"}



 Adding the error output in api_renpho.py is how I determined this.

 if "terminal_user_session_key" not in parsed:
            _LOGGER.error(
                "'terminal_user_session_key' not found in parsed object." + **json.dumps(parsed)**)
            await self.close()
            raise AuthenticationError("'terminal_user_session_key' missing.")


I've created an account and can login to the renpho.com.

**Comment by Amerigo1973** [comment]
Hi, I have the same problem. I will wait for the new version because I would have to change the accounts of the whole family :) For the moment I will get the data from Google Fit, the two apps do not synchronize instantly but they do

**Comment by antoinebou12** [comment]
Try the Renpho - Outdated Version APP and also try the new version with hacs

**Comment by neilzilla** [comment]
This appears to be due to the current integration using the old app and it's API.

I have reverse engineered the new API, but I have not updated the integration yet.

Please follow the repository for a new release in the next month or so.
