### ISSUE TITLE
Unable to import component: cannot import name 'METRIC_TYPE_GROWTH' 

### ISSUE THREAD

**Issue by arungpillai** [neilzilla/hass-renpho#13]
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/renpho/api_renpho.py:15
Integration: renpho (documentation, issues)

Setup failed for custom integration renpho: Unable to import component: cannot import name 'METRIC_TYPE_GROWTH' from 'custom_components.renpho.const' (/config/custom_components/renpho/const.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/renpho/__init__.py", line 13, in <module>
    from .api_renpho import RenphoWeight
  File "/config/custom_components/renpho/api_renpho.py", line 15, in <module>
    from .const import METRIC_TYPE_GROWTH, METRIC_TYPE_GROWTH_GOAL, METRIC_TYPE_WEIGHT
ImportError: cannot import name 'METRIC_TYPE_GROWTH' from 'custom_components.renpho.const' (/config/custom_components/renpho/const.py)

**Comment by antoinebou12** [comment]
Can you check if fix in the new version
