### ISSUE TITLE
"unknown_Error"

### ISSUE THREAD

**Issue by YogiWK** [neilzilla/hass-renpho#27]
Hi,

after I entered the credentials, i got an "unknown_error". Adding the Log down below. I guess there's a problem with the handover because the mail address i entered was correct.

_______________________

Logger: custom_components.renpho.config_flow
Quelle: custom_components/renpho/config_flow.py:94
Integration: Renpho ([Dokumentation](https://github.com/neilzilla/hass-renpho), [Probleme](https://github.com/neilzilla/hass-renpho/issues))
Erstmals aufgetreten: 16:30:12 (2 Vorkommnisse)
Zuletzt protokolliert: 19:10:41
Unexpected exception: Invalid credentials for user **********. Error details: Email was not registered.

Traceback (most recent call last):
  File "/config/custom_components/renpho/api_renpho.py", line 217, in validate_credentials
    return await self.auth()
           ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/renpho/api_renpho.py", line 267, in auth
    raise AuthenticationError("Email was not registered.")
custom_components.renpho.api_renpho.AuthenticationError: Email was not registered.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/renpho/config_flow.py", line 94, in async_step_user
    info = await async_validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/renpho/config_flow.py", line 62, in async_validate_input
    is_valid = await renpho.validate_credentials()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/renpho/api_renpho.py", line 220, in validate_credentials
    raise AuthenticationError(f"Invalid credentials for user {self.email}. Error details: {e}") from e
custom_components.renpho.api_renpho.AuthenticationError: Invalid credentials for user ***********. Error details: Email was not registered.

**Comment by antoinebou12** [comment]
Are you on the renpho outdated app

https://play.google.com/store/apps/details?id=com.qingniu.renpho&hl=en_US
https://apps.apple.com/ca/app/renpho-outdated-version/id1219889310

https://github.com/antoinebou12/hass_renpho/assets/13888068/0bf0e48f-0582-462a-b0a2-6572dd63c860

You can try to auth on this api too
https://hass-renpho.vercel.app/docs

**Comment by YogiWK** [comment]
The login details for the new app lead to "unknown_error". The login details for the old app lead to "Unable to connect to the service". Is the link to FitBit important to use the integration? I don't get a message that the data is being synchronized.

**Comment by antoinebou12** [comment]
The Fitbit integration is not important. I have you try to put a proxy in the optional case and use the hacs install make sure to use the 3.0.1.1

**Comment by mreilaender** [comment]
I get the same error and I see the following logs in HA:

> Cannot connect due to No users found. Details: {'email': 'xxx@xxx.abc}

When I execute the `/users` API call via https://hass-renpho.vercel.app/docs I get:

`{
  "status": "error",
  "message": "404: Users not found",
  "data": null
}`

Though when I execute the `/info` endpoint I get all the information (weight, body fat etc.) properly.

What is the `/users` endpoint for then?

**Comment by Larrax** [comment]
Hi @antoinebou12, I am getting the unknown error as well. I am using the new app's credentials.
I do not have the Outdated app account, and I cannot install the Outdated app anymore (_This app is not available for any of your devices_).

Does that mean I cannot use the integration, or is there a new version, or a workaround? Thanks.
